{% set name = "versioningit" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b91ad7d73e73d21220e69540f20213f2b729a1f9b35c04e9e137eaf28d2214da

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - versioningit = versioningit.__main__:main

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - packaging >=17.1
    - importlib-metadata >=3.6  # [py<310]
    - tomli >=1.2,<3.0  # [py<311]

test:
  requires:
    - pip
    - pytest >=7.0
    - pytest-mock >=3.0
    - python-build >=0.7.0
    - pydantic >=2.0,<3.0
    - editables
    - hatchling
  source_files:
    - test
  imports:
    - versioningit
  commands:
    - pip check
    - versioningit --help
    - pytest -v test

about:
  home: https://github.com/jwodder/versioningit
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Versioning It with your Version In Git
  description: |
    `versioningit` is yet another Python packaging plugin for automatically
    determining your package's version based on your version control
    repository's tags.  Unlike others, it allows easy customization of the
    version format and even lets you easily override the separate functions
    used for version extraction & calculation.
  doc_url: https://versioningit.readthedocs.io
  dev_url: https://github.com/jwodder/versioningit

extra:
  recipe-maintainers:
    - jwodder
